services:
  api:
    build: .
    image: flights_api:latest
    container_name: flights-api
    environment:
      # Talk to Mongo via service name "mongo"
      - MONGODB_URL=mongodb://mongo:27017
      # (optionally) FastAPI envs, e.g. UVICORN_RELOAD, LOG_LEVEL …
    ports:
      - "8080:8000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - flights-net
    # Hot-reloading in dev (comment out in prod)
    volumes:
      - ./app:/app/app:ro

  mongo:
    image: mongo:7.0
    container_name: flights-mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    networks:
      - flights-net

volumes:
  mongo-data:

networks:
  flights-net:
    driver: bridge
